my_first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('landing.urls')),
    path(r'', include('products.urls')),
    path(r'', include('orders.urls')),
    path(r'', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url, include
from products import views

urlpatterns = [
    url(r'^sneakers/(?P<product_id>[\w\-]+)/$', views.product, name='product'),
]

users/urls.py
from django.conf.urls import url, include
from users import views
from django.views.generic.base import TemplateView


urlpatterns = [
    #url(r'^login', views.get_login_or_register_info, name='login'),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'^account/signup/', views.SignUp.as_view(), name='signup'),
    url(r'^account/$', TemplateView.as_view(template_name='login_home.html')),
]

products/models.py
from django.db import models
from django.db.models.signals import *
from PIL import Image


# Create your models here.


class ProductType(models.Model):
    name = models.CharField(max_length=64)
    is_active = models.BooleanField(default=True)
    slug_name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип товара'
        verbose_name_plural = 'Тип товаров'


class Product(models.Model):
    is_active = models.BooleanField(default=True)
    name = models.CharField(max_length=64)
    amount_in_warehouse = models.IntegerField()
    price_per_item = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    product_type = models.ForeignKey(ProductType, blank=True, null=True, default=None, on_delete=models.CASCADE)
    discount = models.IntegerField(default=0)
    is_popular = models.BooleanField(default=False)
    description = models.TextField(blank=True, null=True, default=None)
    URL = models.CharField(verbose_name='URL', max_length=50, )
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def price_with_discount(self):
        price_with_discount = self.price_per_item - (self.price_per_item * self.discount / 100)
        return price_with_discount

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/media/products_images')
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

    def __str__(self):
        return self.product.name


def image_watermark_save(sender, instance, created, **kwargs):
    image_path = instance.image.url
    image_path = image_path[1:]
    watermark_image_path = 'static/img/watermark.png'

    base_image = Image.open(open(image_path, 'rb'))
    watermark_image = Image.open(watermark_image_path)
    width, height = base_image.size

    watermark_transparent = Image.new('RGBA', (width, height), (0, 0, 0, 0))
    watermark_transparent.paste(watermark_image, (width - 250, height - 250))  # 250 - размер watermark+50px

    position = (0, 0)
    base_image.paste(watermark_transparent, position, mask=watermark_transparent)
    base_image.save(image_path)


post_save.connect(image_watermark_save, sender=ProductImage)

products/views.py
from django.shortcuts import render
from .models import *

# Create your views here.


def product(request, product_id):
    product = Product.objects.get(id=product_id)
    session_key = request.session.session_key

    return render(request, 'products/product.html', locals())

templates/products/product.html
{% extends 'base.html' %}
{% block title %}Кроссовки {{ product.name }} купить выгодно{% endblock %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'product.css' %}">{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-5 image">
                {% for product_image in product.productimage_set.all %}
                    <img src="{{ product_image.image.url }}" alt="{{ product.name }}_{{ product_image.id }}"
                         class="img-responsive">
                {% endfor %}
            </div>
            <div class="col-md-7">
                <h3 class="text-center">
                    Кроссовки {{ product.name }}
                </h3>
                <div>
                    <h4 class="product-price" style="font-weight: 700">
                        {% if product.discount == 0 %}
                            Цена: <span style="color: #e83e8c">{{ product.price_per_item }} руб.</span>
                        {% else %}
                            Цена:
                            <span style="text-decoration: line-through; color: #adb5bd">{{ product.price_per_item }} руб.</span>
                            <span style="color: #e83e8c">{{ product.price_with_discount }} руб.</span>
                        {% endif %}
                    </h4>
                    {% if product.amount_in_warehouse > 0 %}
                        {% if user.is_authenticated %}
                            <div>
                                <form id="buying-product" class="form-inline"
                                      action="{% url 'basket_adding' %}">{% csrf_token %}
                                    <input type="number" placeholder="Количество" class="form-control" id="count">
                                    <button class="btn btn-success btn-buy" type="submit"
                                            data-product_id="{{ product.id }}"
                                            data-product_name="{{ product.name }}"
                                            {% if product.discount == 0 %}
                                            data-product_price="{{ product.price_per_item }}"
                                            {% else %}
                                            data-product_price="{{ product.price_with_discount }}"
                                            {% endif %}
                                            id="submit_button">
                                        В корзину
                                    </button>
                                </form>
                            </div>
                        {% endif %}
                        <p class="small">
                            *Оплата при получении товара
                        </p>
                    {% else %}
                        <h4>
                            <div>Наличие уточнять у продавца</div>
                        </h4>
                    {% endif %}
                </div>
                <div>
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#description" aria-controls="description"
                               role="tab" data-toggle="tab">Описание
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#delivery" aria-controls="delivery" role="tab"
                               data-toggle="tab">Доставка
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#messages" aria-controls="messages" role="tab"
                               data-toggle="tab">Комментарии
                            </a>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="description">
                            <p class="tab-p">
                                {{ product.description }}
                            </p>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="delivery">
                            <p class="tab-p">
                                Самовывоз - бесплатно<br>
                                Доставка на дом в день заказа - 10р<br>
                                Доставка на дом в течении 2-3 рабочих дней - 3р<br>
                                *Возможность доставки на дом оговаривается по телефону 88005553535<br>
                            </p>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="messages">
                            <p class="tab-p">
                                Оставляйте ваши комментарии тут :)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}